project:
  type: website

website:
  page-navigation: true
  title: "MOLB 7950"
  description: "Informatics and Statistics for Molecular Biology, Fall 2023."
  site-url: "https://rnabioco.github.io/molb-7950/"
  repo-url: "https://github.com/rnabioco/molb-7950"
  repo-actions: [issue, edit]

  open-graph: true

  twitter-card:
    creator: "@rnabioco"
    image: "images/twitter-card.png"

  page-footer:
    right: "This page is built with [Quarto](https://quarto.org/)."
    left: "&copy; Copyright 2023, Jay Hesselberth"
    background: "#A2A4A3"

  sidebar:
    background: "#CFB87C"
    logo: "content/img/logo.png"
    pinned: true
    align: center
    tools:
      - icon: github
        href: https://github.com/rnabioco/molb-7950
        text: "Course GitHub page"
      - icon: cloud 
        href: https://sso.posit.cloud/cu-anschutz
        text: Posit Cloud SSO login
      - icon: calendar
        href: https://calendly.com/molb7950
        text: Office hours scheduling
      
    style: docked
    search: true
    collapse-level: 1
    contents:
    
      - section: "Course information"
        contents:
          - href: content/course-info/syllabus.qmd
            text: Syllabus
          - href: content/course-info/support.qmd
            text: Support
          - href: content/course-info/team.qmd
            text: Teaching team
          - href: index.qmd
            text: Schedule
          - href: content/course-info/links.qmd
            text: Useful links

      - text: "---"      
      - section: "Bootcamp — R"
        contents:
          - href: content/bootcamp/r/class-01.qmd
            text: "Bootcamp R Day 1"
          - href: content/bootcamp/r/class-02.qmd
            text: "Bootcamp R Day 2"
          - href: content/bootcamp/r/class-03.qmd
            text: "Bootcamp R Day 3"
          - href: content/bootcamp/r/class-04.qmd
            text: "Bootcamp R Day 4"
          - href: content/bootcamp/r/class-05.qmd
            text: "Bootcamp R Day 5"
 
      - section: "Bootcamp — Statistics"
        contents:
          - href: content/bootcamp/stats/class-01.qmd
            text: "Bootcamp Stats Day 1"
          - href: content/bootcamp/stats/class-02.qmd
            text: "Bootcamp Stats Day 2"
          - href: content/bootcamp/stats/class-03.qmd
            text: "Bootcamp Stats Day 3"
          - href: content/bootcamp/stats/class-04.qmd
            text: "Bootcamp Stats Day 4"
          - href: content/bootcamp/stats/class-05.qmd
            text: "Bootcamp Stats Day 5"
            
      - text: "---"      
      - section: "Block DNA"
        contents:
          - href: content/block-dna/variant-calling/class-01.qmd
            text: "Variant Calling Day 1"
          - href: content/block-dna/variant-calling/class-02.qmd
            text: "Variant Calling Day 2"
            
      - text: "---"      
      - section: "Assignments"
        contents:
          - href: content/course-info/problem-sets.qmd
            text: Problet Set Overview
          - href: content/course-info/final-projects.qmd
            text: Final Project Overview 
            
format:
  html:
    theme:
      light: [cosmo, style/quarto-main.scss]
      dark: [cosmo, style/dark.scss, style/quarto-main.scss]
    mainfont: "Atkinson Hyperlegible"
    code-copy: true
    code-overflow: wrap
    toc: true
#  revealjs:
#    output-ext: slides.html
 
execute:
  freeze: auto

editor: source  