project:
  type: website

website:
  page-navigation: true
  title: "MOLB 7950"
  description: "Informatics and Statistics for Molecular Biology, Fall 2023."
  site-url: "https://rnabioco.github.io/molb-7950/"
  repo-url: "https://github.com/rnabioco/molb-7950"
  repo-actions: [issue]

  open-graph: true

  twitter-card:
    creator: "@rnabioco"
    image: "images/twitter-card.png"

  page-footer:
    right: "This page is built with [Quarto](https://quarto.org/)."
    left: "&copy; Copyright 2023, Jay Hesselberth"
    background: "#A2A4A3"

  sidebar:
    background: "#CFB87C"
    # logo: "images/logo.png"
    pinned: true
    align: center
    tools:
      - icon: github
        href: https://github.com/rnabioco
        text: "RBI GitHub"
      - icon: cloud 
        href: https://sso.posit.cloud/cu-anschutz
        text: Posit Cloud SSO login
      
    style: docked
    search: true
    collapse-level: 2
    contents:
    
      - section: "Course information"
        contents:
          - href: content/course-info/course-syllabus.qmd
            text: Syllabus
          - href: content/course-info/course-support.qmd
            text: Support
          - href: content/course-info/course-team.qmd
            text: Teaching team
          - href: index.qmd
            text: Schedule
          - href: content/course-info/course-links.qmd
            text: Useful links
          - href: content/course-info/final-projects.qmd
            text: Useful links

      - text: "---"      
      - section: "Bootcamp — Statistics"
        contents:
          - href: content/bootcamp/stats/stats-class-01.qmd
            text: "Bootcamp Stats Day 1"
          - href: content/bootcamp/stats/stats-class-02.qmd
            text: "Bootcamp Stats Day 2"
          - href: content/bootcamp/stats/stats-class-03.qmd
            text: "Bootcamp Stats Day 3"
          - href: content/bootcamp/stats/stats-class-04.qmd
            text: "Bootcamp Stats Day 4"
          - href: content/bootcamp/stats/stats-class-05.qmd
            text: "Bootcamp Stats Day 5"
            
      - text: "---"      
      - section: "Problem Sets"
        contents:
          - href: content/course-info/problem-sets.qmd
            text: Problet Set Overview
            
format:
  html:
    theme:
      light: [cosmo, style/quarto-main.scss]
      dark: [cosmo, style/dark.scss, style/quarto-main.scss]
    mainfont: "Atkinson Hyperlegible"
    code-copy: true
    code-overflow: wrap
    toc: true
  # pdf: default
  revealjs:
    output-ext: slides.html
  
execute: 
  freeze: auto

editor:
  markdown:
    wrap: 72
    canonical: true
