project:
  type: website

website:
  page-navigation: true
  title: "MOLB 7950"
  description: "Informatics and Statistics for Molecular Biology, Fall 2023."
  site-url: "https://rnabioco.github.io/molb-7950/"
  repo-url: "https://github.com/rnabioco/molb-7950"
  repo-actions: [issue]

  open-graph: true

  twitter-card:
    creator: "@rnabioco"
    image: "images/twitter-card.png"

  page-footer:
    right: "This page is built with [Quarto](https://quarto.org/)."
    left: "&copy; Copyright 2023, Jay Hesselberth"
    background: "#A2A4A3"

  sidebar:
    background: "#CFB87C"
    logo: "content/img/logo.png"
    pinned: true
    align: center
    tools:
      - icon: cloud 
        href: https://sso.posit.cloud/cu-anschutz
        text: Posit Cloud SSO login
      - icon: slack
        href: https://molb7950.slack.com/ssb/redirect 
        text: In-class support via Slack
      - icon: calendar
        href: https://calendly.com/molb7950
        text: Office hours scheduling
      - icon: github
        href: https://github.com/rnabioco
        text: "RBI GitHub"
      
    style: docked
    search: true
    collapse-level: 2
    contents:
    
      - section: "Course information"
        contents:
          - href: content/course-info/syllabus.qmd
            text: Syllabus
          - href: content/course-info/support.qmd
            text: Support
          - href: content/course-info/team.qmd
            text: Teaching team
          - href: index.qmd
            text: Schedule
          - href: content/course-info/links.qmd
            text: Useful links

      - text: "---"      
      - section: "Bootcamp — Statistics"
        contents:
          - href: content/bootcamp/stats/class-01.qmd
            text: "Bootcamp Stats Day 1"
          - href: content/bootcamp/stats/class-02.qmd
            text: "Bootcamp Stats Day 2"
          - href: content/bootcamp/stats/class-03.qmd
            text: "Bootcamp Stats Day 3"
          - href: content/bootcamp/stats/class-04.qmd
            text: "Bootcamp Stats Day 4"
          - href: content/bootcamp/stats/class-05.qmd
            text: "Bootcamp Stats Day 5"
            
      - text: "---"      
      - section: "Block — RNA"
        contents:
          - href: content/block-rna/single-cell/class-01.qmd
            text: "Single-cell mRNA seq Day 1"
          - href: content/block-rna/single-cell/class-02.qmd
            text: "Single-cell mRNA seq Day 2"
          
      - text: "---"      
      - section: "Problem Sets"
        contents:
          - href: content/course-info/problem-sets.qmd
            text: Problet Set Overview
            
format:
  html:
    theme:
      light: [cosmo, style/quarto-main.scss]
      dark: [cosmo, style/dark.scss, style/quarto-main.scss]
    mainfont: "Atkinson Hyperlegible"
    code-copy: true
    code-overflow: wrap
    toc: true
  revealjs:
    output-ext: slides.html
  