on:
  pull_request:
    branches: main

name: molb-7950-pr

jobs:
  netlify:
    runs-on: ubuntu-latest
    steps:
      - name: ✅ Check out repository
        uses: actions/checkout@v3
        
      - name: 🆀 Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
     
      - name: 🆀 Quarto extensions
        shell: bash
        run: |
          quarto add --no-prompt quarto-ext/fontawesome
          quarto add --no-prompt sellorm/quarto-social-embeds
    
      - name: 🔧 Install R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
          r-version: 'renv'
    
      - name: 🔁 Install system dependencies 
        run: |
          sudo apt-get install libcurl4-openssl-dev
          sudo apt-get install libmagick++-dev
          sudo apt-get install libglpk-dev 
          
      - name: 🔁 Install R Dependencies
        uses: r-lib/actions/setup-renv@v2
        with:
          cache-version: 1
    
      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v3.0
        with:
          publish-dir: './_site'
          production-branch: main
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message:
            'Deploy from GHA: ${{ github.event.pull_request.title || github.event.head_commit.message }} (${{ github.sha }})'
          # these default to 'true'
          enable-commit-comment: false
          enable-github-deployment: false
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.npm install netlify-cli -g}}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}